# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

# Пользователи
## Регистрация пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "appolon@overlook.net",
  "username": "Jack",
  "password": "shining",
  "isPro": true
}

###

# ## Регистрация пользователя 2
# POST http://localhost:5000/users/register HTTP/1.1
# Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="username"

# petro
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="email"

# petronkano@overlook.net
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="password"

# testpass
# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="isPro"

# true
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--
# Content-Disposition: form-data; name="avatar"; filename="76.jpg"
# Content-Type: image/png

# < /Users/filyukov/tmp/76.jpg
# ------WebKitFormBoundary7MA4YWxkTrZu0gW--

# ###

## Авторизация пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "jsskgj@overlook.net",
  "password": "shining"
}

###
## Отправка аватарки пользователю

POST http://localhost:5000/users/63f381e4a6eb9c65cf84a767/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Impzc2tnakBvdmVybG9vay5uZXQiLCJpZCI6IjYzZjM4MWU0YTZlYjljNjVjZjg0YTc2NyIsImlhdCI6MTY3NjkyNjAyNiwiZXhwIjoxNjc3MDk4ODI2fQ.hl3Rk_Z579d88pL4BhPyOydRbOqTezWV61dBNvwAPqY
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="76.jpg"
Content-Type: image/png

< /Users/filyukov/tmp/76.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Проверка токена пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Impzc2tnakBvdmVybG9vay5uZXQiLCJpZCI6IjYzZjM4MWU0YTZlYjljNjVjZjg0YTc2NyIsImlhdCI6MTY3NjkwMzI2MywiZXhwIjoxNjc3MDc2MDYzfQ.RwBNgMsSfw2gpXGj7TcJjHJp5Gh6yhsnvODbiH3fNFI

###

# Предложения
## Получение списка предложений

GET http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json

###

# Предложения
## Получение 2х предложений из списка

GET http://localhost:5000/offers/?limit=2 HTTP/1.1
Content-Type: application/json

###

# Предложения
## Создание предложения

POST http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Impzc2tnakBvdmVybG9vay5uZXQiLCJpZCI6IjYzZjM4MWU0YTZlYjljNjVjZjg0YTc2NyIsImlhdCI6MTY3NjkwMzI2MywiZXhwIjoxNjc3MDc2MDYzfQ.RwBNgMsSfw2gpXGj7TcJjHJp5Gh6yhsnvODbiH3fNFI

{
  "title": "some new title",
  "city": {
    "name": "Cologne",
    "location": {
      "latitude": 50.938361,
      "longitude": 6.959974
    }
  },
  "thumbnail": "avatarname.png",
  "pictures": ["picture1.jpg", "picture2.jpg", "picture3.jpg", "picture4.jpg", "picture5.jpg", "picture6.jpg"],
  "premium": true,
  "rating":  3.5,
  "type": "room",
  "price": 36556,
  "description": "some description description description",
  "rooms": 4,
  "guests": 2,
  "conveniences": [],
  "location": {
    "latitude": 53.550341,
    "longitude": 10.000654
  }
}

###

# Предложения
## Получение детальной информации о предложении

GET http://localhost:5000/offers/63f3873ec17693252f40c401 HTTP/1.1
Content-Type: application/json

###


# Предложения
## Редактирование предложения

PATCH  http://localhost:5000/offers/63f3873ec17693252f40c401 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Impzc2tnakBvdmVybG9vay5uZXQiLCJpZCI6IjYzZjM4MWU0YTZlYjljNjVjZjg0YTc2NyIsImlhdCI6MTY3NjkwMzI2MywiZXhwIjoxNjc3MDc2MDYzfQ.RwBNgMsSfw2gpXGj7TcJjHJp5Gh6yhsnvODbiH3fNFI

{
  "title": "some new title",
  "price": 36557
}

###

# Предложения
## Удаление предложения

DELETE http://localhost:5000/offers/63f3873ec17693252f40c401 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Impzc2tnakBvdmVybG9vay5uZXQiLCJpZCI6IjYzZjM4MWU0YTZlYjljNjVjZjg0YTc2NyIsImlhdCI6MTY3NjkwMzI2MywiZXhwIjoxNjc3MDc2MDYzfQ.RwBNgMsSfw2gpXGj7TcJjHJp5Gh6yhsnvODbiH3fNFI

###

## Создать комментарий
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Impzc2tnakBvdmVybG9vay5uZXQiLCJpZCI6IjYzZjM4MWU0YTZlYjljNjVjZjg0YTc2NyIsImlhdCI6MTY3NjkwMzI2MywiZXhwIjoxNjc3MDc2MDYzfQ.RwBNgMsSfw2gpXGj7TcJjHJp5Gh6yhsnvODbiH3fNFI

{
  "text": "Как обстоят дела с коробками? Фирменная упаковка сохранена?",
  "offerId": "63f38b5dc17693252f40c412",
  "userId": "63f381e4a6eb9c65cf84a767",
  "rating": 3.3
}

###

## Список комментариев к объявлению
GET http://localhost:5000/offers/63f38b5dc17693252f40c412/comments HTTP/1.1
Content-Type: application/json

###
